# -*- coding: utf-8 -*-
"""kmeans_cluster.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s7iom1_ruImrFtbJisTUfSlfk3p69AL-
"""

#import necessary libraries
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import seaborn as sns
import numpy as np
from sklearn.datasets import make_blobs #to generate test data

#Generating test data
X,Y= make_blobs(n_samples=1000,centers=4,cluster_std=0.9,random_state=1)
print(X[:10])
print(Y[:10])

plt.scatter(X[ : ,0],X[ : ,1],s=20) # this is the dataset. we can clearly see the 4 clusters being formed

kmean=KMeans(n_clusters=4,max_iter=500,random_state=1) # first I tried to make the code without any function.
kmean.fit(X)
y=kmean.predict(X)

plt.scatter(X[ : ,0],X[ : ,1],s=20)
plt.scatter(kmean.cluster_centers_[ : ,0],kmean.cluster_centers_[ : ,1],c='red',s=100)

def cal_kmeans(X1,Y1): # the above thing made into a function
  plt.scatter(X1[ : ,0],X1[ : ,1],s=20)
  kmean=KMeans(n_clusters=4,max_iter=500,random_state=1)
  kmean.fit(X1)
  y=kmean.predict(X1)
  centers=kmean.cluster_centers_
  IDs=kmean.labels_
  return centers,IDs

X2,Y2= make_blobs(n_samples=1000,centers=4,cluster_std=0.7,random_state=5)
centers,IDs=cal_kmeans(X2,Y2)
plt.scatter(X2[ : ,0],X2[ : ,1],s=20)
plt.scatter(centers[ : ,0],centers[ : ,1],c='red',s=100)
print(IDs[:10])